//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UITool_2011.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_UITool_2011TYPE             130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_CONTROLMENUDLG              310
#define IDD_MESSAGEEDITDLG              312
#define IDD_STATEEDITDLG                313
#define IDD_SEARCHDLG                   315
#define IDD_DIALOG1                     316
#define IDD_ADDSTRING                   316
#define IDC_UI                          1001
#define IDC_CHECK_LOGIN                 1002
#define IDC_TREE                        1003
#define IDC_BUTTON                      1004
#define IDC_SCROLLBAR                   1005
#define IDDELETE                        1005
#define IDC_COMBOBOX                    1006
#define IDC_LISTBOX                     1007
#define IDC_COMBO_MESSAGE               1007
#define IDC_EDIT                        1008
#define IDC_COMBO_ACTION                1008
#define IDC_GRID                        1009
#define IDADD                           1009
#define IDC_CTRLDELETE                  1010
#define IDC_TREE1                       1010
#define IDC_TREE_MESSAGE                1010
#define IDC_EDIT_ID                     1011
#define IDC_EDIT_POSX                   1012
#define IDC_EDIT_POSY                   1013
#define IDC_CHECK_VISIBLE               1014
#define IDC_EDIT_SIZEW                  1015
#define IDC_EDIT_SIZEH                  1016
#define IDC_EDIT_TEXTUREADDRESS         1017
#define IDC_EDIT_STRINGCOLOR_R          1018
#define IDC_EDIT_STRINGCOLOR_G          1019
#define IDC_EDIT_STRINGCOLOR_B          1020
#define IDC_BUTTON_TEXTURE              1022
#define IDC_STATE_ID                    1023
#define IDC_STATE_POSITION              1024
#define IDC_STATE_SIZE                  1025
#define IDC_STATICEDIT                  1026
#define IDC_COLORLOAD                   1027
#define IDC_LIST1                       1028
#define IDC_LIST_ADD                    1028
#define IDC_LIST2                       1029
#define IDC_BUTTON1                     1030
#define IDC_BUTTON_SEARCH               1030
#define IDC_BUTTON_ADD                  1030
#define IDC_EDIT_SEARCH                 1031
#define IDC_EDIT1                       1035
#define IDC_BUTTON_DELETE               1036
#define IDC_STATIC_ADDSTRING            1037
#define IDC_EDIT_ADDSTRING              1038

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
