#ifndef _AGCD_ITEM_DROP_H_
#define _AGCD_ITEM_DROP_H_

#include <ApBase/ApBase.h>

enum AgcdItemDropCategoryId {
	AGCD_ITEM_DROP_CATEGORYID_NORMAL_WEAPON,
	AGCD_ITEM_DROP_CATEGORYID_RARE_WEAPON,
	AGCD_ITEM_DROP_CATEGORYID_UNIQUE_WEAPON,
	AGCD_ITEM_DROP_CATEGORYID_ELITE_WEAPON,
	AGCD_ITEM_DROP_CATEGORYID_NORMAL_ARMOR,
	AGCD_ITEM_DROP_CATEGORYID_RARE_ARMOR,
	AGCD_ITEM_DROP_CATEGORYID_UNIQUE_ARMOR,
	AGCD_ITEM_DROP_CATEGORYID_ELITE_ARMOR,
	AGCD_ITEM_DROP_CATEGORYID_REALMARMOR,
	AGCD_ITEM_DROP_CATEGORYID_ELEMENTAL_STONE,
	AGCD_ITEM_DROP_CATEGORYID_PRAYER_STONE,
	AGCD_ITEM_DROP_CATEGORYID_REINFORCEMENT_POTION,
	AGCD_ITEM_DROP_CATEGORYID_NORMAL_RING_NECKLACE,
	AGCD_ITEM_DROP_CATEGORYID_SHIELD,
	AGCD_ITEM_DROP_CATEGORYID_RARE_RING_NECKLACE,
	AGCD_ITEM_DROP_CATEGORYID_JEWEL,
	AGCD_ITEM_DROP_CATEGORYID_POTION,
	AGCD_ITEM_DROP_CATEGORYID_PASSPORT,
	AGCD_ITEM_DROP_CATEGORYID_MATERIAL,
	AGCD_ITEM_DROP_CATEGORYID_CHEST,
	AGCD_ITEM_DROP_CATEGORYID_REVERSE_ORB,
	AGCD_ITEM_DROP_CATEGORYID_UNIQUE_ACCESSORY,
	AGCD_ITEM_DROP_CATEGORYID_COUNT
};

static const char * g_pszAgcdItemDropCategoryTags[] = {
	"Normal Weapon",
	"Rare Weapon",
	"Unique Weapon",
	"Elite Weapon",
	"Normal Armor",
	"Rare Armor",
	"Unique Armor",
	"Elite Armor",
	"Realm Armor",
	"Elemental Stone",
	"Prayer Stone",
	"Reinforcement Potion",
	"Normal Ring/Necklace",
	"Shield",
	"Rare Ring/Necklace",
	"Jewel",
	"Potion",
	"Passport",
	"Material",
	"Chest",
	"Reverse Orb",
	"Unique Accessory"
};

#endif /* _AGCD_ITEM_DROP_H_ */